---
driver:
  name: docker
#  cc_pattern: "<%= File.basename(Dir.pwd) %>"
  cc_pattern: tomcat_pattern_ansible

provisioner:
  name: ansible_playbook
  playbook: ./site.yml
  roles_path: ./roles
  group_vars_path: ./group_vars
  host_vars_path: ./host_vars
  filter_plugins: ./filter_plugins
  additional_copy_path: [./webservers.yml, ]
  require_ansible_omnibus: true
  require_ruby_for_busser: true

platforms:
  - name: centos-7
    driver_config:
      image: centos:centos7
      dockerfile: test/platforms/Dockerfile
      privileged: true
      run_command: /sbin/init; sleep 3
  - name: centos-6
    driver_config:
      image: centos:centos6
      dockerfile: test/platforms/Dockerfile

verifier:
  ruby_bindir: '/usr/bin'

suites:
  - name: web_default
    attributes:
      extra_vars:
        ap_server_ip: '192.168.0.2'
        db_server_ip: '192.168.0.3'
    provisioner:
      hosts: webserver
  - name: ap_default
    attributes:
      extra_vars:
        ap_server_ip: '192.168.0.2'
        db_server_ip: '192.168.0.3'
    provisioner:
      hosts: apserver
  - name: db_default
    attributes:
      extra_vars:
        ap_server_ip: '192.168.0.2'
        db_server_ip: '192.168.0.3'
    provisioner:
      hosts: dbserver
