AllCops:
  Exclude:
    - cookbooks/**/*
    - site-cookbooks/**/metadata.rb
    - vendor/**/*

LineLength:
  Max: 130

MethodLength:
  Max: 20

AbcSize:
  Enabled: false

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

NumericLiterals:
  MinDigits: 7
